spring:
  application:
    name: todo-project
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/todo
    username: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 60000
  threads:
    virtual:
      enabled: true
